# Generated by Django 5.2.1 on 2025-05-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('key', models.SlugField(max_length=100, primary_key=True, serialize=False, verbose_name='Key name')),
                ('name', models.CharField(max_length=100, verbose_name='Social media')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
                'ordering': ['name'],
            },
        ),
    ]
